debugging: true
webroot: "../webroot"
concept_schemes:
  - name: 'access_rights'
    skos_folder_path: '../skos/skosified_v1_revised_2020-12-04'
    version: '1.0'
    title: 'Access Rights'
    updated: 2018-12-20
    description: 'The Access Rights vocabulary defines concepts to declare the access status of a resource. Multilingual labels regard regional distinctions in language and term.'
    namespace: 'http://purl.org/coar/access_right/'
    creators:
      - Apollaro, Alberto
      - Aubin, Sophie
      - Azrilevich, Paola
      - Bernal, Isabel
      - Dan, Liu
      - Fripp, Dom
      - Gürdal, Gültekin
      - Habre, Sawsan
      - Hayashi, Yutaka
      - Holt, Ilkay
      - Hua, Nie
      - Jones, Hilary
      - Kataoka, Tomoko
      - Le Borgne, Laurence
      - Liping, Ku (Alan)
      - Mornati, Susanna
      - Ojsteršek, Milan
      - Príncipe, Pedro
      - Schirrwagen, Jochen
      - Shiota,Tomoya
      - Solodovnik, Iryna
      - Steinhoff, Wilko
      - Vedovotto, Nathalie
    contributors:
      - COAR Controlled Vocabularies Interest Group
  - name: 'version_types'
    skos_folder_path: '../skos/skosified_v1_revised_2020-12-04'
    version: '1.0'
    title: 'Version Types'
    updated: 2018-07-18
    description: 'The Version Type vocabulary defines concepts to declare the version of a resource. Multilingual labels regard regional distinctions in language and term. The concepts are adopted from the \"Journal Article Versions (JAV): Recommendations of the NISO/ALPSP JAV Technical Working Group\", https://www.niso.org/publications/niso-rp-8-2008-jav'
    namespace: 'http://purl.org/coar/version/'
    creators:
      - Apollaro, Alberto
      - Aubin, Sophie
      - Azrilevich, Paola
      - Bernal, Isabel
      - Dan, Liu
      - Fava, Ilaria
      - Fripp, Dom
      - Gürdal, Gültekin
      - Habre, Sawsan
      - Holt, Ilkay
      - Hua, Nie
      - Jones, Hilary
      - Kataoka, Tomoko
      - Le Borgne, Laurence
      - Liping, Ku (Alan)
      - Príncipe, Pedro
      - Schirrwagen, Jochen
      - Shiota,Tomoya
      - Solodovnik, Iryna
      - Steinhoff, Wilko
      - Vedovotto, Nathalie
    contributors:
      - COAR Controlled Vocabularies Interest Group
  - name: 'resource_types'
    skos_folder_path: '../skos/skosified_v1_revised_2020-12-04'
    version: '1.0'
    title: 'Resource Types'
    updated: 2019-07-19
    description: 'The Resource Type vocabulary defines concepts to identify the genre of a resource. Such resources, like publications, research data, audio and video objects, are typically deposited in institutional and thematic repositories or published in ejournals. This vocabulary supports a hierarchical model that relates narrower and broader concepts. Multilingual labels regard regional distinctions in language and term. Concepts of this vocabulary are mapped with terms and concepts of similar vocabularies and dictionaries.'
    namespace: 'http://purl.org/coar/resource_type/'
    creators:
      - Aubin, Sophie
      - Azrilevich, Paola
      - Bernal, Isabel
      - Le Borgne, Laurence
      - Habre, Sawsan
      - Hayashi, Yutaka
      - Holt, Ilkay
      - Hua, Nie
      - Jones, Hilary
      - Kataoka, Tomoko
      - Liping, Ku (Alan)
      - Mornati, Susanna
      - Ojsteršek, Milan
      - Príncipe, Pedro
      - Schirrwagen, Jochen
      - Steinhoff, Wilko
      - Vedovotto, Nathalie
      - Fava, Ilaria (departed)
      - Shiota,Tomoya (departed)
      - Solodovnik, Iryna (departed
      - Subirats, Imma (departed)
      - Wang, Shenghui (departed)
    contributors:
      - COAR Controlled Vocabularies Interest Group
  - name: 'access_rights'
    skos_folder_path: '../skos/skosified_phaidra_export_2021-02-03'
    version: ''
    title: 'Access Rights'
    updated: 2018-12-20
    description: 'The Access Rights vocabulary defines concepts to declare the access status of a resource. Multilingual labels regard regional distinctions in language and term.'
    namespace: 'http://purl.org/coar/access_right/'
    creators:
      - Apollaro, Alberto
      - Aubin, Sophie
      - Azrilevich, Paola
      - Bernal, Isabel
      - Dan, Liu
      - Fripp, Dom
      - Gürdal, Gültekin
      - Habre, Sawsan
      - Hayashi, Yutaka
      - Holt, Ilkay
      - Hua, Nie
      - Jones, Hilary
      - Kataoka, Tomoko
      - Le Borgne, Laurence
      - Liping, Ku (Alan)
      - Mornati, Susanna
      - Ojsteršek, Milan
      - Príncipe, Pedro
      - Schirrwagen, Jochen
      - Shiota,Tomoya
      - Solodovnik, Iryna
      - Steinhoff, Wilko
      - Vedovotto, Nathalie
    contributors:
      - COAR Controlled Vocabularies Interest Group
  - name: 'version_types'
    skos_folder_path: '../skos/skosified_phaidra_export_2021-02-03'
    version: ''
    title: 'Version Types'
    updated: 2018-07-18
    description: 'The Version Type vocabulary defines concepts to declare the version of a resource. Multilingual labels regard regional distinctions in language and term. The concepts are adopted from the \"Journal Article Versions (JAV): Recommendations of the NISO/ALPSP JAV Technical Working Group\", https://www.niso.org/publications/niso-rp-8-2008-jav'
    namespace: 'http://purl.org/coar/version/'
    creators:
      - Apollaro, Alberto
      - Aubin, Sophie
      - Azrilevich, Paola
      - Bernal, Isabel
      - Dan, Liu
      - Fava, Ilaria
      - Fripp, Dom
      - Gürdal, Gültekin
      - Habre, Sawsan
      - Holt, Ilkay
      - Hua, Nie
      - Jones, Hilary
      - Kataoka, Tomoko
      - Le Borgne, Laurence
      - Liping, Ku (Alan)
      - Príncipe, Pedro
      - Schirrwagen, Jochen
      - Shiota,Tomoya
      - Solodovnik, Iryna
      - Steinhoff, Wilko
      - Vedovotto, Nathalie
    contributors:
      - COAR Controlled Vocabularies Interest Group
  - name: 'resource_types'
    skos_folder_path: '../skos/skosified_phaidra_export_2021-02-03'
    version: ''
    title: 'Resource Types'
    updated: 2019-07-19
    description: 'The Resource Type vocabulary defines concepts to identify the genre of a resource. Such resources, like publications, research data, audio and video objects, are typically deposited in institutional and thematic repositories or published in ejournals. This vocabulary supports a hierarchical model that relates narrower and broader concepts. Multilingual labels regard regional distinctions in language and term. Concepts of this vocabulary are mapped with terms and concepts of similar vocabularies and dictionaries.'
    namespace: 'http://purl.org/coar/resource_type/'
    creators:
      - Aubin, Sophie
      - Azrilevich, Paola
      - Bernal, Isabel
      - Le Borgne, Laurence
      - Habre, Sawsan
      - Hayashi, Yutaka
      - Holt, Ilkay
      - Hua, Nie
      - Jones, Hilary
      - Kataoka, Tomoko
      - Liping, Ku (Alan)
      - Mornati, Susanna
      - Ojsteršek, Milan
      - Príncipe, Pedro
      - Schirrwagen, Jochen
      - Steinhoff, Wilko
      - Vedovotto, Nathalie
      - Fava, Ilaria (departed)
      - Shiota,Tomoya (departed)
      - Solodovnik, Iryna (departed
      - Subirats, Imma (departed)
      - Wang, Shenghui (departed)
    contributors:
      - COAR Controlled Vocabularies Interest Group